require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.0
  SuggestExtensions: false

Style/Documentation: 
  Enabled: false
  

Rails/I18nLocaleTexts:
  Enabled: false